# @see https://dev.to/louisbertin/macos-series-how-to-enhance-your-vim-editor-488k
# @see https://www.lazyvim.org/
if [ -x "$(command -v nvim)" ]; then
    alias vim='/opt/homebrew/bin/nvim'
    alias vi='vim'
    export EDITOR=/opt/homebrew/bin/nvim
    export VISUAL=/opt/homebrew/bin/nvim
else
    echo "Neovim not installed (brew install neovim)"
fi

if [ ! -d $HOME/.config/nvim ]; then
  git clone https://github.com/LazyVim/starter ~/.config/nvim
  rm -rf ~/.config/nvim/.git
fi

